---
# upload the script and set the remote host to a slave node1
- name: upload the slavenode script
  become: yes
  copy:
    src: ./slavenode1.sh
    dest: /home/ubuntu/
    mode: 0777

- name: execute the slavenode script
  become: yes
  shell: /home/ubuntu/slavenode1.sh