- hosts: all_servers
  remote_user: ubuntu
  gather_facts: true
  roles:
    - role: servers-addproxy
    - role: servers-docker-env
    

- hosts: slavenode1
  remote_user: ubuntu
  gather_facts: true
  roles:
    - role: servers-couchdb-slave1

- hosts: slavenode2
  remote_user: ubuntu
  gather_facts: true
  roles:
    - role: servers-couchdb-slave2

- hosts: masternode
  remote_user: ubuntu
  gather_facts: true
  roles:
    - role: servers-couchdb-master